#ifndef CONSTANTS_H
#define CONSTANTS_H

#define PLAYER_BULLET_POOL_SIZE 5
#define ENEMY_BULLET_POOL_SIZE 5
#define ENEMY_POOL_SIZE 5

#define TURN_COOLDOWN_TIME 10
#define BULLET_COOLDOWN_TIME 10

#endif
